Seperate SinkA/Prefetch to fix timing
OpenXiangShan/CoupledL2 pull request #201
Opened 2024-07-16 09:10 UTC by yulightenyu

a. do not check aMerge when prefetch
b. prefetch duplicate with MSHR check move from s1 to s2
c. when prefetch dup MSHR -> drop @S2

2024-07-17 07:46 UTC, linjuanZ requested changes

2024-07-17 07:46 UTC, linjuanZ commented on src/main/scala/coupledL2/RequestBuffer.scala
> +//  io.ASet := io.in.bits.set
Remove stale comments

2024-07-17 07:46 UTC, linjuanZ commented on src/main/scala/coupledL2/RequestBuffer.scala
> +//  val in      = io.in.bits
Remove stale comments

2024-07-17 07:46 UTC, linjuanZ commented on src/main/scala/coupledL2/RequestBuffer.scala
> +//      s.valid && s.bits.isAcqOrPrefetch && sameAddr(in, s.bits)) ++
Remove stale comments

2024-07-17 07:46 UTC, linjuanZ commented on src/main/scala/coupledL2/SinkA.scala
> +/*  if (prefetchOpt.nonEmpty) {
Remove stale comments

2024-07-18 08:11 UTC, yulightenyu commented on src/main/scala/coupledL2/RequestBuffer.scala
> +//  io.ASet := io.in.bits.set
deleted

2024-07-18 08:11 UTC, yulightenyu commented on src/main/scala/coupledL2/RequestBuffer.scala
> +//  val in      = io.in.bits
deleted

2024-07-18 08:11 UTC, yulightenyu commented on src/main/scala/coupledL2/RequestBuffer.scala
> +//      s.valid && s.bits.isAcqOrPrefetch && sameAddr(in, s.bits)) ++
deleted

2024-07-18 08:11 UTC, yulightenyu commented on src/main/scala/coupledL2/SinkA.scala
> +/*  if (prefetchOpt.nonEmpty) {
deleted

2024-07-19 09:05 UTC, linjuanZ approved these changes

2024-07-19 09:06 UTC, merged