feat(ECC): add ECC for coupledL2(TL version)
OpenXiangShan/CoupledL2 pull request #278
Opened 2024-10-29 11:56 UTC by Ma-YX

add optional ECC for tag & data

TODO: fix width of address in L2CacheErrorInfo

2024-12-02 09:38 UTC, linjuanZ requested changes

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/Common.scala
> +  val address = UInt(48.W)
The width of address should be parameterized. Direct use of hardcoded constants should be avoided.
```suggestion
  val address = UInt(addressBits.W)
```

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/CoupledL2.scala
> +    }
Why is the same code repeated twice?

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/CoupledL2.scala
> +      io.error.address := l2ECCArb.io.out.bits.address
It seems that address is assigned as follows in MainPipe:
```
io.error.bits.address := Cat(task_s5.bits.tag, task_s5.bits.set, task_s5.bits.off)
```
This is the address inside a slice. The effective address should be restored by considering bank index using `restoreAddress`.

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/DataStorage.scala
> +    Cat(VecInit(Seq.tabulate(4)(i => io.wdata.data((blockBytes * 2) * (i + 1) - 1, (blockBytes * 2) * i))).map(data => cacheParams.dataCode.encode(data)))
`4` should be parameterized.

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/DataStorage.scala
> +    VecInit(Seq.tabulate(4)(i => arrayRead.data(encDataBankBits * (i + 1) - 1, encDataBankBits * i))).
`4` should be parameterized.

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/tl2chi/TXDAT.scala
> +  io.out.bits.respErr := Mux(taskR.task.corrupt, Mux(taskR.task.denied, RespErrEncodings.NDERR, RespErrEncodings.DERR), RespErrEncodings.OK)
Please keep the line width of the code within 120 characters.

2024-12-02 09:38 UTC, linjuanZ commented on src/main/scala/coupledL2/tl2chi/chi/Message.scala
> +  def DATACHECK_WIDTH = DATA_WIDTH / 64
I don't think this complies with CHI spec:
```
When Data Check is supported:
The DAT packet carries eight Data Check bits per 64 bits of data.
```

2024-12-02 09:51 UTC, Ma-YX commented on src/main/scala/coupledL2/CoupledL2.scala
> +    }
This is caused by not fully deleting duplicated code during two rebase merge, I'll delete one later

2024-12-02 09:51 UTC, linjuanZ reviewed
Please make sure OpenLLC handles DataCheck correctly before this pr is merged. @Kumonda221-CrO3

2024-12-02 10:22 UTC, Ma-YX commented on src/main/scala/coupledL2/CoupledL2.scala
> +    }
fixed in 495d96f31b8a1a433fd4115e1bff3df4ee32db2b

2024-12-02 10:26 UTC, Ma-YX commented on src/main/scala/coupledL2/DataStorage.scala
> +    Cat(VecInit(Seq.tabulate(4)(i => io.wdata.data((blockBytes * 2) * (i + 1) - 1, (blockBytes * 2) * i))).map(data => cacheParams.dataCode.encode(data)))
fixed in 9e575788365bc8981a528bc7f71781f73676d6ac

2024-12-02 10:26 UTC, Ma-YX commented on src/main/scala/coupledL2/DataStorage.scala
> +    VecInit(Seq.tabulate(4)(i => arrayRead.data(encDataBankBits * (i + 1) - 1, encDataBankBits * i))).
fixed in 9e575788365bc8981a528bc7f71781f73676d6ac

2024-12-03 03:28 UTC, Ma-YX commented on src/main/scala/coupledL2/CoupledL2.scala
> +      io.error.address := l2ECCArb.io.out.bits.address
fixed in 27566879e80f05f21079c63108b9d1eef28ce501 and 57b4a63dcb50047225754593b70b11d3e5e71a71

2024-12-03 03:28 UTC, Ma-YX commented on src/main/scala/coupledL2/tl2chi/TXDAT.scala
> +  io.out.bits.respErr := Mux(taskR.task.corrupt, Mux(taskR.task.denied, RespErrEncodings.NDERR, RespErrEncodings.DERR), RespErrEncodings.OK)
fixed in 57b4a63dcb50047225754593b70b11d3e5e71a71

2024-12-03 03:28 UTC, Ma-YX commented on src/main/scala/coupledL2/tl2chi/chi/Message.scala
> +  def DATACHECK_WIDTH = DATA_WIDTH / 64
fixed in 57b4a63dcb50047225754593b70b11d3e5e71a71

2024-12-03 07:40 UTC, Ma-YX commented on src/main/scala/coupledL2/Common.scala
> +  val address = UInt(48.W)
fixed in 8514d3a0a99b66c26b97d54c32848b302c889bf6

2024-12-03 09:36 UTC, linjuanZ approved these changes

2024-12-04 04:22 UTC, Kumonda221-CrO3 commented
Test passed on OpenLLC with ```dataCheck = Some("oddparity")```.

2024-12-04 04:23 UTC, Kumonda221-CrO3 approved these changes

2024-12-04 05:39 UTC, merged