fix(SnpResp): SnpOnce/SnpOnceFwd send data resp to HN
OpenXiangShan/CoupledL2 pull request #309
Opened 2024-12-30 09:27 UTC by Ma-YX

cache state: UD -> I

SnpOnce/SnpOnceFwd should send SnpRespData/SnpRespData*Fwd to HN, otherwise corresponding data will get lost (neither RNs nor HN will keep)

2025-01-02 02:55 UTC, linjuanZ requested changes

2025-01-02 02:55 UTC, linjuanZ commented on src/main/scala/coupledL2/tl2chi/MSHR.scala
> +  val doRespData = doRespData_dirty || doRespData_retToSrc_fwd || doRespData_retToSrc_nonFwd || doRespData_once
For SnpOnce, data should be returned when initial cache state is SC with `RetToSrc` asserted, or UC. Data should not be returned when initial cache state is SC and `RetToSrc` deasserted.

2025-01-02 02:55 UTC, linjuanZ commented on src/main/scala/coupledL2/tl2chi/MSHR.scala
> +  val fwdPassDirty = (isSnpToNFwd(req_chiOpcode) || isSnpOnceX(req_chiOpcode)) && hitDirtyOrWriteBack
DCT response of SnpOnceFwd should not pass dirty, because the response is always CompData. The peer-RN should not take responsibility of holding dirty copy.

2025-01-02 04:34 UTC, Ma-YX commented on src/main/scala/coupledL2/tl2chi/MSHR.scala
> +  val fwdPassDirty = (isSnpToNFwd(req_chiOpcode) || isSnpOnceX(req_chiOpcode)) && hitDirtyOrWriteBack
fixed in f5bfd566d086f625230d37cbca429bde7095572f

2025-01-02 05:40 UTC, Ma-YX commented on src/main/scala/coupledL2/tl2chi/MSHR.scala
> +  val doRespData = doRespData_dirty || doRespData_retToSrc_fwd || doRespData_retToSrc_nonFwd || doRespData_once
fixed in 6d191843604373b23e62078bdc7b6be6c08359d1

2025-01-02 05:52 UTC, Kumonda221-CrO3 requested changes

2025-01-02 05:52 UTC, Kumonda221-CrO3 commented on src/main/scala/coupledL2/tl2chi/MSHR.scala
> +  val snpNested = req.snpHitRelease && req.snpHitReleaseWithData
Suggested better enchantment signals naming here:
```suggestion
  val hitWriteBack = req.snpHitRelease && req.snpHitReleaseWithData
  val hitDirtyOrWriteBack = hitDirty || hitWriteBack
```

2025-01-02 06:20 UTC, Ma-YX commented on src/main/scala/coupledL2/tl2chi/MSHR.scala
> +  val snpNested = req.snpHitRelease && req.snpHitReleaseWithData
fixed in 9c8d6f2feabedae70f9310582b27c24e98ee3f69

2025-01-06 06:13 UTC, linjuanZ approved these changes

2025-01-06 06:13 UTC, linjuanZ commented on src/main/scala/coupledL2/Common.scala
> +  val snpHitReleaseDirty = Bool()
This should be parameterized (but not in this pr). @Kumonda221-CrO3

2025-01-06 06:15 UTC, Kumonda221-CrO3 commented on src/main/scala/coupledL2/Common.scala
> +  val snpHitReleaseDirty = Bool()
Copy.

2025-01-06 06:19 UTC, Kumonda221-CrO3 approved these changes

2025-01-06 06:27 UTC, merged